
# ????????? ??????????? ? PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5555/fitclub_db
spring.datasource.username=pavel
spring.datasource.password=a6dbe82d
spring.datasource.driver-class-name=org.postgresql.Driver

# ????????? Liquibase
spring.liquibase.change-log=classpath:db/changelog.xml
spring.liquibase.enabled=true

# ?????????? ???????????????? R2DBC (???? ?? ????????????)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration

